### ISSUE TITLE
Elro Home Easy HE877 problem

### ISSUE THREAD

**Issue by Takisg** [pimatic/pimatic-homeduino#18]
Elro Home Easy HE877 switch working with protocol "switch 2".

I have a problem with the receiving mode.

On receiver mode decode the off command from the remote control  but the on command decode the same result off.

Any help......

**Comment by sweetpi** [comment]
Please post the issue at the https://github.com/pimatic/rfcontroljs reporsitory with a full debug output of pimatic-homeduino. Thanks.
