### ISSUE TITLE
Error: Cannot find module 'rfcontroljs'

### ISSUE THREAD

**Issue by Nears** [pimatic/pimatic-homeduino#19]
After adding the homeduino plugin to my pimatic config i get the error above.
Does homeduino requires this plugin? Why isn't it linked via the packages.json?

How can i solve the problem?
Thanks for help.

Update: Having a sleepless night I tried to install it manually and it works fine for now. But why is a manual installation needed?

**Comment by sweetpi** [comment]
> Update: Having a sleepless night I tried to install it manually and it works fine for now. But why is a manual installation needed?

It shouldn't. rfcontroljs is a dependency of homeduinojs which is a dependency of pimatic-homeduino. Do you have the log file from the failing installation?

**Comment by Nears** [comment]
Is it saved somewhere?? If not i don't have one. Sorry for that.

**Comment by sweetpi** [comment]
If you run pimatic with the `start` option, it should have been written into a logfile `pimatic-daemon.log`.

**Comment by Nears** [comment]
Ok i hada look i the log but it just says
```
 ...
[pimatic] info: loading plugin: "pimatic-homeduino" (0.8.33)
[pimatic] error: Cannot find module 'rfcontroljs'
...
```

**Comment by sweetpi** [comment]
ok
