### ISSUE TITLE
Computer with Arduino connected running homeduino

### ISSUE THREAD

**Issue by pieman64** [pimatic/pimatic-homeduino#20]
The readme file states:

A. Computer with connected arduino (with homeduino sketch) and 433mhz transmitter and receiver (recommended)
B. Raspberry Pi (or Banana Pi or Hummingboard) with 433mhz transmitter and receiver

Although I have several Raspberry Pi's I am looking to set this up with an Arduino and a laptop. Can you please confirm this is possible and the basic steps I need to take.

I have tried adding the RFControl sketch to the Arduino and also homeduino but I was struggling with missing libraries. Some of the files in the github for RFControl were updated in the last few hours so maybe I will try again but a basic setup guide would help. I notice lots of references to the Raspberry Pi and the name pimatic-homeduino suggests strong links to the Pi so maybe it is not possible to use this software with a PC and an Arduino.

**Comment by sweetpi** [comment]
With a Linux PC its well tested and possible. I used the plugin several times on my development laptop. Theoretically it should work on windows, too. But I've never tested that. 

Don't use the RFControl sketch directly, use the homeduino one instead. You can either follow the flashing instruction for debian/raspbian (linux) https://github.com/pimatic/homeduino#flashing
or you can use the arduino IDE to flash the sketch. Then you have to clone the repository with git:

```
git clone --recursive https://github.com/pimatic/homeduino.git
```

and then copy the libraries and sketch files to the correct locations. See the arduino IDE manual for more details.
