### ISSUE TITLE
Homedunio + Mediacenter (XBMC)

### ISSUE THREAD

**Issue by Rantir** [pimatic/pimatic-homeduino#22]
Hi guys,

i hope you can give a helping hand.

I want to know if it is possible to set up the Rapi with xbmc like RaspMc and use the homeduino without limitations?

SO far ive got the reciver and sender connected to my Pi directly but the XBMC is damn slow/unuseable.
If i connect a Arduino Nano clone via USB, will this will restore the Rapi's Power to make XBMC play FULL HD + DTS Movies as before? Or will this limit the Power of the Rapi no matter what and i shall buy a nother Rapi?

Thank you guys!

**Comment by sweetpi** [comment]
CPU load with an arduino and homeduino should be much less (about 3%). I never tested if it works well with XBMC, but I would think that it works well, because you would not have a high priority process that consumes much of the cpu time running anymore.

**Comment by Rantir** [comment]
Well i just worry if Homedunio will do any other fancy / heavy stuff beside CPU usage.

Will this one suits my needs well?

http://www.amazon.de/Aukru-Nano-elektronische-interaktive-Dupont-Kabel-328P-v3-0/dp/B00PL70XWW/ref=sr_1_7?ie=UTF8&qid=1421681535&sr=8-7&keywords=Arduino+nano+usb

**Comment by sweetpi** [comment]
> Will this one suits my needs well?

Yes. Would be cool if you report back if XBMC is working smoothly with homeduino.

**Comment by Rantir** [comment]
Well it was late when i came home but ive got it.
If you like i whould make a little guide with some Pics .

Here is the short ugly Version of what i did:

Pre: an Old Raspmc Version, if i remember right it must be around Nov/2014

1. sudo apt-get update

{From this at 23.01.2015: https://github.com/pimatic/homeduino#flashing }

2. sudo apt-get install arduino-core avr-libc avrdude binutils-avr gcc-avr libconfig-yaml-perl libftdi1 libyaml-perl screen python-serial

3. git clone --recursive https://github.com/pimatic/homeduino.git

4. go to the Makefile and change

BOARD_TAG to your Arduino Type/CPU , you can use  make show_boards to see the options
MONITOR_PORT to the right USBport (remember which one)

5. make upload

[be happy ;)]


{ 23.01.2015: https://github.com/pimatic/pimatic-homeduino#aconnected-arduino-recommended }

edit your config..json file to this.

{
  "plugin": "homeduino",
  "driver": "serialport",
  "driverOptions": {
    "serialDevice": "/dev/ttyUSB0",
    "baudrate": 115200
  },
  "receiverPin": 0,
  "transmitterPin": 4
}


6. wire the stuff

i connected 5V and GND from the Reciver/transmitter to my Raspberry
and D2 Nano pin to Reciver DATA pin and D4 Nano pin to Transmitter DATA pin .



7. ????

8. PROFIT (everything shall be fine by now)






Comments:
XBMC need some time to show up and was a bit slow for about 2 min but than its fine.
Well 1080P + DTS worked fine, navigation is smooth.
Musik worked

**Comment by Rantir** [comment]
Well , after i got my p2 and osmc on it i try to reinstall pimatic, but atm it doesnt work as it should.

But the p2 is way more advanced and should handle it perfectly, i will report, but first of all i need to find a way to recive and send signals again

**Comment by Icesory** [comment]
@Rantir for more help you can use the Forum
http://forum.pimatic.org/category/18/howto-pimatic
