### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by robertmolenaar** [pimatic/pimatic-homeduino#23]
Hi,

It would be great if it is possible to use more GPIO pins from the Arduino board. Currently I use the GPIO plugin for some standard devices (a pushbutton and a (wired) contact connected to the raspberry). If Pimatic-homeduino can also implement this it would be great!

My request for Pimatic-homeduino please add a GPIO pushbutton and a GPIO contact (read pin).

I know there is a Pin switch device already.

Little background: I trying to install Pimatic on a Synology. Currently it already runs using chroot (USB/Arduino not yet working.. but I have high hopes). If I can use homeduino for GPIO actions then I don't need the raspberry GPIO's anymore (and a total switch to a Synology device might be possible).

I tried to see if I can create a device/protocol/... myself in Pimatic-Homeduino, but.. well.. I got stuck.

If I read the description of Homeduino correct it is possible to read and write to pins (DR pin).

PS: Thanks for the really great work!

**Comment by DavidZH** [comment]
I am very interested in this topic. Especially running pimatic on a Synology. What are the issue you run into?

**Comment by robertmolenaar** [comment]
Hi. I succeeded in running Pimatic on a Synology by using chroot. I didn't use the node.js package of Synology (because pimatic still needs to compile code on start).  The only thing I did got working yet is the Arduino with USB. But I did try much because I still needed some extra functionality (see request).

To be honest I totally missed the reply of sweetpi on this so I didn't try the solution he provided in his answer. So first I will try this solution on the PI and Arduino. If it works all ok I will try switching to the Synology.

**Comment by sweetpi** [comment]
@robertmolenaar I read your request, but didn't find time for that, yet. At the moment some user have stability issues I want to solve first. Then their will be new features.

homeduino can read digital and analog pins already, so it shouldn't be too hard to extend the plugin.

**Comment by robertmolenaar** [comment]
@sweetpi Ok. thanks..

**Comment by robertmolenaar** [comment]
Short update for.... With some rules I managed to create a pushbutton on homeduino. And I use the AnalogSensor for some wired contacts. So with some creative usage of available devices I manged to 'move' from the Raspberry GPIO to the Nano. Next step will be switching to the Synology. (If succeeded I  will report it on the form.

**Comment by sweetpi** [comment]
@robertmolenaar Nice to hear.
