### ISSUE TITLE
Raspberry Pi 2 Not supported with GPIO filter

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic-homeduino#26]
Tested the Raspberry P 2 today and i got this error:

[pimatic-homeduino] debug: data: "wiringX: hardware not supported"

**Comment by sweetpi** [comment]
@sweebee I've updated the vhduino binary with the new wiringX version. Could you test if it is working?

**Comment by sweebee** [comment]
Updating...

**Comment by sweetpi** [comment]
do you get an error message if you start it not in daemon mode? (just `./node_modules/pimatic/pimatic.js`)

**Comment by sweebee** [comment]
```
21:40:14.093 2015-02-11 Wednesday
21:40:19.047 [pimatic] Starting pimatic version 0.8.43
21:40:21.330 [pimatic] loading plugin: "pimatic-homeduino" (0.8.38)
21:40:22.019 [pimatic] loading plugin: "pimatic-links" (0.8.5)
21:40:22.123 [pimatic] loading plugin: "pimatic-cron" (0.8.5)
21:40:23.004 [pimatic] loading plugin: "pimatic-mobile-frontend" (0.8.42)
21:40:24.800 [pimatic] loading plugin: "pimatic-sunrise" (0.8.0)
21:40:24.871 [pimatic] loading plugin: "pimatic-pushbullet" (0.8.4)
21:40:26.523 [pimatic] loading plugin: "pimatic-shell-execute" (0.8.6)
21:40:26.657 [pimatic-cron] the time is: Wed Feb 11 2015 21:40:26 GMT+0100 (CET)
21:40:26.671 [pimatic-sunrise] Your location is set to lat: 52.302646, long: 6.841062
21:40:26.675 [pimatic-pushbullet] apikey= raCwZbH2xv8KhPNU0GC4Soq8VeFv2wUw
21:40:26.857 [pimatic] new device "Nachtlamp Wiebe"...
21:40:26.913 [pimatic] new device "Zithoek"...
21:40:26.974 [pimatic] new device "Deurbel ontvanger"...
21:40:27.015 [pimatic] new device "Automatische modus"...
21:40:27.066 [pimatic] new device "Alarm"...
21:40:27.111 [pimatic] new device "Bank"...
21:40:27.154 [pimatic] new device "Wandkast"...
21:40:27.201 [pimatic] new device "Plafond lamp"...
21:40:27.247 [pimatic] new device "Woonkamer"...
21:40:27.294 [pimatic] new device "Bewegingsmelder hal"...
21:40:27.395 [pimatic] new device "Deurbel"...
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by sweetpi** [comment]
What does 

`ls -la ./node_modules/pimatic-homeduino/node_modules/homeduino/bin`

say?

**Comment by sweebee** [comment]
```
total 64
drwxr-xr-x 1 root root    14 Feb 11 21:06 .
drwxrwsrwx 1 root root   174 Feb 11 21:24 ..
-rwxr-xr-x 1 root root 62180 Feb 11 21:06 vhduino
```
I hope you can quickly fix this, can't turn my lights off now  :P

**Comment by sweetpi** [comment]
@sweebee let's chat in the forum

**Comment by sweetpi** [comment]
I released pimatic-homeduino v0.8.39 which includes the old version of homeduino, so it should be working again.

**Comment by bjornhij** [comment]
I managed to get it working again by compiling again with the latest version of wiringX. I can send you a tar (or zip) of the working sourcecode if this helps?

**Comment by bjornhij** [comment]
I've created a pull request:

https://github.com/pimatic/virtualhomeduino/pull/1

**Comment by Yves911** [comment]
Can we update the title of this issue from "Raspberry Pi 2 Not supported" to "Raspberry Pi 2 not  support homeduino using GPIO"
I have a raspberry 2 with homeduino and an arduino it works 100% fine.

**Comment by sweebee** [comment]
Changed the title. i'm using a arduino now with my pi2.

**Comment by sweetpi** [comment]
It also should work with the newes version of the plugin. So closes, please reopen if there are any issues with it.

**Comment by bjornhij** [comment]
@sweetpi the version of the binary in homeduinojs is not the same as the one I compiled yesterday and does not work (my version is 117.175 kb, the one in homeduinojs is 107.355 kb). I've created a pull request with the correct binary.

**Comment by sweetpi** [comment]
merged!

**Comment by CurlyMoo** [comment]
It would ofc be only a matter of time before pimatic would adopt my `wiringX` originally developed for pilight :wink:

**Comment by koffienl** [comment]
Just like pilight adopted the idea of rules? ;)

**Comment by sweebee** [comment]
And the way the config looks/works? :P

**Comment by CurlyMoo** [comment]
> Just like Pilight adopted the idea of rules

Never knew pimatic invented the idea of rules...

> And the way the config looks/works?

That was invented by @sweetpi and I. Not by either of us individual.

**Comment by sweetpi** [comment]
wiringX is great and its even greater that it's released as a standalone lib. So big thanks @CurlyMoo for creating and managing it.

As I always said, I think pilight is a great solution and its nice that we can share ideas and experience :+1: We have a different focus on a lot of thinks and therefore its goof that both solutions exists and user can choose what's the best for there needs.

**Comment by CurlyMoo** [comment]
I totally agree. Glad we can keep it this way. I want to wish the same to our communities!

Also, please invite users of pimatic to create new wiringX modules, because it would benefit the OSS community greatly.

**Comment by Yves911** [comment]
I started with pilight and received good help from @CurlyMoo to develop the TFA protocol into pilight. I switched to pimatic because it's more what i am looking for.
Since more than 1 year i benefited of good advises and help from @sweetpi @CurlyMoo and the both communities.
Keep it up guys !
