### ISSUE TITLE
Send repeats

### ISSUE THREAD

**Issue by annuh** [pimatic/pimatic-homeduino#27]
Hi,

Is it possible to choose the number of send repeats?

I have a KaKu switch outside my house and sometimes it doesn't react on commands sends by this (awesome) plugin. If I later send on/off commands manually it works perfectly. 

Therefore I believe it sometimes misses commands and this could probably be solved by sending the same command multiple times.

Thank you!

**Comment by sweetpi** [comment]
@Icesory has added a option for this.
