### ISSUE TITLE
on/off events independent of current state

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic-homeduino#51]
Would it be possible to always trigger the on event for a switch even if the state currently is already on? Same for off.
Example:
I have RF wall switches on both sides of the room. I turn it on on one side of the room and want to turn it off on the other side of the room but current state of this switch offs already off.
Currently I can see that off is received but nothing happens in the rule which uses "if switch2 is turned off..." 
Maybe this could also be a general functionality for all switch type devices in pimatic.

**Comment by Icesory** [comment]
For the receive event you must use
"if switch2 receive on then... "
This event is always triggered and is independent of the state of the switch.

**Comment by thexperiments** [comment]
Great! You can close this one, works like a charm. We should put some chat sheet/help link into the rule dialog. I'm using pimatic quite long now and didn't know about this.

**Comment by Icesory** [comment]
You are right, the Homeduino readme lacks every aspect of rules. So I think we should add this.
