### ISSUE TITLE
Pwm Dimmer to set Color with 3 pwm pins

### ISSUE THREAD

**Issue by bastardop** [pimatic/pimatic-homeduino#58]
Is it possible to implement a 3 Channel pwm to choose a Color for a rgb led Strip? One colorchannel per pwm Pin with rgb values from 0-255 and a suitable chooser in pimatic?

**Comment by mwittig** [comment]
It is generally possible but out of scope for pimatic-homeduino. As there has been no contribution on the matter so far I am closing this now
