### ISSUE TITLE
[0.9] Frontend device config switch typeof(id) = string prevents detection (switch1)

### ISSUE THREAD

**Issue by ChiefZ** [pimatic/pimatic-homeduino#61]
Hi there,

I added a HomeduinoRFSwitch (switch1) device but the event didn't register. Debug showed successfull detection so I went digging.
Turns out that the id was set as a string via the frontend edit device dialog which prevented the doesProtocolMatch detection in homeduino.coffee. The id in the config.json for this switch was indeed a string and after changing it to a number everything started working

I don't know where this originates, but I don't have that problem with a switch13, where the id is added as a number to the config.

I am running pimatic 0.9 beta.

**Comment by bjornhij** [comment]
Had the same issue. Same as #65

**Comment by bjornhij** [comment]
See pull request https://github.com/pimatic/rfcontroljs/pull/107

**Comment by mwittig** [comment]
Fixed by https://github.com/pimatic/rfcontroljs/commit/31d9eaa335621625ecb5d3bc4cf39b97cb38da12
See also https://github.com/pimatic/rfcontroljs/pull/107
