### ISSUE TITLE
Extension of HomeduinoRFShutter with xOnLabel and xOffLabel doesn't work

### ISSUE THREAD

**Issue by michbeck100** [pimatic/pimatic-homeduino#70]
device-config-schema.coffee [states](https://github.com/pimatic/pimatic-homeduino/blob/master/device-config-schema.coffee#L198) that a HomeduinoRFShutter can be extended with different labels for the two buttons it comes with. This doesn't work. 
When used pimatic fails to create the device because it doesn't have a state attribute and then it crashes [here](https://github.com/pimatic/pimatic/blob/26b81a38e477a9ef32cc985a8d1452b014cac099/lib/devices.coffee#L1236).
Since a state attribute doesn't make sense for shutters, i would say we need an extension for shutters like "xUpLabel" and "xDownLabel". But this would include changes in pimatic and pimatic-mobile-frontend.

**Comment by mwittig** [comment]
I am getting a "Cannot read property 'labels' of undefined" error when I am trying save the device. I think the use use of xOn and xOff is simply wrong in this context and thus needs to be removed from the device template. I'll do that asap.

See also https://github.com/pimatic/pimatic/issues/294

It should be possible to implement something appropriate for shutter possition, but I consider this as a feature request to be file on pimatic forum

**Comment by mwittig** [comment]
To be released

**Comment by qistoph** [comment]
A bit late to the conversation, but just now running into this issue myself.

Why were these labels removed? I'm using the KaKu ASUN-650 for my drapes and would really like to change the options 'Up'/'Down' to 'Closed'/'Open'. Those would be more applicable to drapes closing from left and right.

**Comment by mwittig** [comment]
Please have a look at the first and second post for background. So far no feature request for "xUpLabel" and "xDownLabel" has been raised. 

https://forum.pimatic.org/category/14/feature-requests

**Comment by mwittig** [comment]
I have implemented the stuff assuming there would be two upvotes at least :)
