### ISSUE TITLE
Homeduino analogDimmer value wrong?

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic-homeduino#73]
from the forum 
is there any issue regarding the analogdimmer? 
seems that it can only be used from 0 to 39 ?
pls. review and referr to the forum
https://forum.pimatic.org/topic/2615/malfunction-homeduino-analog-dimmer

**Comment by mwittig** [comment]
I broke this is as part of the fixture for issue #63. The prior fix needs to be partially reverted and the use of the numberMapping help function as part of the HomeduinoRFDimmer needs to be fixed

**Comment by mwittig** [comment]
I think this issue has been solved. Please re-open otherwise
