### ISSUE TITLE
Use Plugin without Arduino

### ISSUE THREAD

**Issue by poudenes** [pimatic/pimatic-homeduino#79]
Hi There,

I read its recommended to use Arduino, but then you also can use it without?
I have a 433Mhz transmitter and receiver at my RPI.

Did test with ./codesend 123 and on second terminal ./RFsniffer
That is working. 

Can someone assist me? :)

**Comment by mwittig** [comment]
See our forum for further details
* https://forum.pimatic.org/topic/202/4-homeduino-433-mhz-sending-receiving-and-even-more
