### ISSUE TITLE
tranceiver and 868 

### ISSUE THREAD

**Issue by passie** [pimatic/pimatic-homeduino#81]
Would it be possible to support a transceiver with this plugin ?
currently I have 1 receiver and 1 transmitter but would like to replace this with one transceiver. 

secondly would it be possible to support 868 mhz transceivers as well with this plugin ?

**Comment by mwittig** [comment]
Generally, is possible if a developer volunteers to rewrite and extend the homeduino core. However, as far as I know, the protocol encoding / decoding with 868 Mhz differs a lot from the 433 Mhz stuff homeduino supports today. 

Note, pimatic already supports some 868 Mhz protocols with _[pimatic-coc](https://github.com/dfischbach/pimatic-coc)_ which also supports CUL. So maybe creating a CUL clone is good starting point for you. See https://wiki.fhem.de/wiki/Selbstbau_CUL and http://blog.gummibaer-tech.de/jeelink-433-868-mhz-selbstbau/

Please close the ticket if the answer is sufficient. Thanks

**Comment by passie** [comment]
Thank you !
