### ISSUE TITLE
Plugin Installation Failing (using npm)

### ISSUE THREAD

**Issue by 0verrfl0w** [pimatic/pimatic-homeduino#82]
Hello all,

I tried to install the homeduino plugin, which did not work, on a fresh pimatic install. But for some reason it kept failing at node-gyp and serialport@2.0.6. 

Installing the plugin from github also did not achieve a working result.
Also I found out, that homeduino@0.0.65 is not available at npm yet, as specified in the package.json.

Attached the npm output:

```13297 error Linux 4.9.14-v7+
13298 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-homeduino" "--unsafe-perm"
13299 error node v7.7.4
13300 error npm  v4.1.2
13301 error code ELIFECYCLE
13302 error serialport@2.0.6 install: `node-pre-gyp install --fallback-to-build`
13302 error Exit status 1
13303 error Failed at the serialport@2.0.6 install script 'node-pre-gyp install --fallback-to-build'.
13303 error Make sure you have the latest version of node.js and npm installed.
13303 error If you do, this is most likely a problem with the serialport package,
13303 error not with npm itself.
13303 error Tell the author that this fails on your system:
13303 error     node-pre-gyp install --fallback-to-build
13303 error You can get information on how to open an issue for this project with:
13303 error     npm bugs serialport
13303 error Or if that isn't available, you can get their info via:
13303 error     npm owner ls serialport
13303 error There is likely additional logging output above.
13304 verbose exit [ 1, true ]

**Comment by mwittig** [comment]
> 13299 error node v7.7.4
13300 error npm  v4.1.2

You have the wrong version of nodejs & npm installed! Unfortunately, pimatic only supports nodejs 4.x along with npm v2 which is included with nodejs 4.x. See also https://pimatic.org/guide/getting-started/installation/

Please also consider using our user forum https://forum.pimatic.org/ for trouble shooting as this is backed by a large user base and you'll usually get speedy response while github is only tracked by a few devs.

**Comment by mwittig** [comment]
Note beyond, the current version of pimatic-homeduino uses homeduino@0.0.63. You have probably checked the dependency specs on master which are ahead of the release.

```
pimatic-homeduino@0.9.11 pimatic-homeduino
└── homeduino@0.0.63 (otaat-repl@1.0.2, bluebird@2.9.34, rfcontroljs@0.0.58, serialport@2.0.6)

**Comment by 0verrfl0w** [comment]
Thank for the quick response. I was unaware that pimatic would not work reliably with a higher version of node and therefore fail here. Personally I am not a NodeJS expert.
Thank you for the explanations!
