### ISSUE TITLE
Client error: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by Holygoast82** [pimatic/pimatic-homeduino#92]
since Version 0.9.16 i have he following error

Client error: Cannot read property 'value' of null

**Comment by mwittig** [comment]
Can you please check the log for error message and copy the full message(s)? Thanks

**Comment by Holygoast82** [comment]
which log is that? pimatic-deamon.log? or is there e seperate homeduino logfile?

**Comment by mwittig** [comment]
pimatic-daemon.log

**Comment by Holygoast82** [comment]
Ok. After update 0.9.17 problem is solved. thanks anyway for the support

**Comment by mwittig** [comment]
Great. Thanks for feedback
