### ISSUE TITLE
Uncaught exception installing homeduino 0.9.18 on pimatic 0.9.50 and 0.9.52

### ISSUE THREAD

**Issue by pihome3** [pimatic/pimatic-homeduino#94]
After a clean install of Pimatic 0.9.50 following the instructions in the wiki I tried to install the pimatic-homeduino plugin (0.9.18).
The installation fails with an uncaught exception. I attached the log with the errors.
[log.txt](https://github.com/pimatic/pimatic-homeduino/files/3513038/log.txt)

**Comment by pihome3** [comment]
Today I have update Pimatic to 0.9.52. After this I have tried to install the homeduino plugin (0.9.18) again. This results in an other error.
[Log Pimatic 0.9.52 - Pimatic-Homeduino 0.9.18.txt](https://github.com/pimatic/pimatic-homeduino/files/3563841/Log.Pimatic.0.9.52.-.Pimatic-Homeduino.0.9.18.txt)

**Comment by mrdago** [comment]
Same for me, installing  **"pimatic-homeduino@0.9.18"** results in error: 

**An uncaught exception occurred: AssertionError [ERR_ASSERTION]: Array.isArray(tags)**

Here the versions of the installation environment:

 - Linux buster 4.19.68-v7+
 - pimatic version 0.9.52
 - Node.js version 10.16.3

**Comment by akicker** [comment]
My way was to downgrade **node to version 8** (via nvm - already before installing pimatic)
Current I am using on my latest Rpi 4 B
latest stable kernel 4.19.66, **node 8.16.1**, pimatic 0.9.52, homeduino 0.9.18

**Comment by mrdago** [comment]
In addition, I realized that independent from the reported installation error

```
11:02:10.546 [] info: ../src/serialport_unix.cpp:176:60: warning: ‘[object Object]’ directive output may be truncated writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=]
11:02:10.842 [pimatic] error: An uncaught exception occurred: AssertionError [ERR_ASSERTION]: Array.isArray(tags)
11:02:10.842 [pimatic] error:>    at new AssertionError (internal/errors.js:102:11)
``` 
 the homeduino plugin is working as expected (node 8 and 10).

Anyway, it would make sense to correct the code to supress the installation error.
